### PR TITLE
New admin menu by Golfin

### PR DESCRIPTION
**Pull request by Jhobean**
Golfin took some times to made an admin menu combining all the best part of different old menu. We now have a brand new menu with lot of cool feature.

Thx Goldfin!  Me i'm just the messenger :-)

New menu include and not limited to:
- Tag list
- event list
- Multilangage and auto dectection (If your langage is not on the list, it's by defaut to ENG)

See the new admin menu screeshot:
http://eranova.cz/multilanguage-admin

I took some time to make item and character menu to look the same appearance.

old Admin menu now in legacy folder.

image

### CODE REVIEW

**Comment by orishi** [comment]
Crashes default client (7.0.20.0) because of non-existent gumps. Orion Client is fine, but it should be fixed anyway.
Golfin himself stated that on his website:

> PS: Gump ID 30550, ie the background of the whole admin console is a new image. If you do not have it in the older version of the UO, change ID 30550 to another gump ID that your UO contains.

```
Page 0 // Basic layout
Resizepic 0 0 30546 650 507
Gumppictiled 5 5 640 497 2604
Gumppictiled 5 5 640 25 30550 // change
Gumppictiled 5 480 640 22 30550 // change
Gumppictiled 5 35 640 440 30550 // change
Checkertrans 5 5 640 497
```

**Comment by Jhobean** [comment]
Here the old gump available on old client
image

**Comment by cbnolok** [comment]
Can we use a gump that's always been available? Imho it's better to preserve maximum compatibility in core scripts

**Comment by Jhobean** [comment]
> Can we use a gump that's always been available? Imho it's better to preserve maximum compatibility in core scripts

Yes, It's what I did in the last commit. Just put the standard old gump.. Removed the 30550 and 30546

**Pull request merged**
