### PR TITLE
Add OSI like inscription/Carpentry crafting menu

### PR DESCRIPTION
**Pull request by Jhobean**
- Add inscription menu
- Improuve the crafting dialog
- Add a function to check recipe for better custom optimisation

### CODE REVIEW

**Comment by cbnolok** [comment]
What's the purpose of the files with sm_ prefix? That's supposed to be used for files containing skillmenu sections

**Comment by Jhobean** [comment]
Yes its the skill menu of the osilike dialog

**Comment by cbnolok** [comment]
I mean, is that softcoded or hardcoded? Is a file with only defs? In that case the prefix should be different

**Comment by Jhobean** [comment]
Yes it's sofcode... Only def.  But its in the skillmenu folder.  I can rename them but for more comprehension its better to keep them sm because it replace legacy sm.

**Pull request merged**
