### PR TITLE
Add World save File to script pack

### PR DESCRIPTION
**Pull request by Jhobean**
I add the Basic world save to the script pack for 2 reasons
1- Keep version when we upgrade it
2- On appveyor, if we want put the save on the folder, it must be there

### CODE REVIEW

**Comment by cbnolok** [comment]
Can't we add a customizable world generator with the instructions on a txt, instead of assuming what people would need?

**Comment by Jhobean** [comment]
We could add too. But For now the faster way to give a good easy to run core is an existing save. Personnaly I never used save generator and I don't think there one functionnal for now. So it's why save should be add and eventually add save generator in the same folder?

**Comment by Jhobean** [comment]
My goal is achieve a server "ready out of the box" for the dev tryin to start a server sunday morning when they want to play UO.

**Comment by Jhobean** [comment]
Here how me and @nirad see the "out of the box" system.
When you download the sphere server, youll have the same folder on the .zip than now. In folder, youll have script pack and this save.
Ini will be set on io 127.0.0.1 and auto create account.
The only thing admin will have to do is set mul directory on the ini and dclic the .exe.

**Comment by GitMadKing** [comment]
ON THIS

> Here how me and @Nirad see the "out of the box" system.
> When you download the sphere server, youll have the same folder on the .zip than now. In folder, youll have script pack and this save.
> Ini will be set on io 127.0.0.1 and auto create account.
> The only thing admin will have to do is set mul directory on the ini and dclic the .exe.

I WOULD PUT DEFAULT MUL DIRECTORY IN ../

so yo play sphere is enought to extract it in the ultima online folder called "sphere" (or whatever, the point is being inside the actual mul/UO folder" :)

**Comment by Nirad** [comment]
> ON THIS
> 
> > Here how me and @Nirad see the "out of the box" system.
> > The only thing admin will have to do is **set mul** directory on the ini and dclic the .exe.
> 
> I WOULD PUT DEFAULT MUL DIRECTORY IN the sphere.ini to => MulFiles=../
> 
> so for you to play sphere is enought to extract it in the ultima online folder called "sphere" (or whatever, the point is being inside the actual mul/UO folder" :)
> 
> so no settings has to be done actually

no a bad idea to copy sphere inside a uo/mul directory ../

**Pull request merged**
